// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtnpYneIkaCCa_LGf579d2geGVRL6qzOQ',
    appId: '1:725537660419:web:e9ad502ba4ceb7bf7c7836',
    messagingSenderId: '725537660419',
    projectId: 'voicerecognition-31a54',
    authDomain: 'voicerecognition-31a54.firebaseapp.com',
    storageBucket: 'voicerecognition-31a54.appspot.com',
    measurementId: 'G-5TCD0VEVZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0IyWXotLHrkSOCufOZV4TPgATgq2VJ1w',
    appId: '1:725537660419:android:1a40f7c2dc1051837c7836',
    messagingSenderId: '725537660419',
    projectId: 'voicerecognition-31a54',
    storageBucket: 'voicerecognition-31a54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLnSxz7TpbLFlHNORtwamp1bVpf-CKVbY',
    appId: '1:725537660419:ios:1d469c2334331fcb7c7836',
    messagingSenderId: '725537660419',
    projectId: 'voicerecognition-31a54',
    storageBucket: 'voicerecognition-31a54.appspot.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLnSxz7TpbLFlHNORtwamp1bVpf-CKVbY',
    appId: '1:725537660419:ios:1d469c2334331fcb7c7836',
    messagingSenderId: '725537660419',
    projectId: 'voicerecognition-31a54',
    storageBucket: 'voicerecognition-31a54.appspot.com',
    iosBundleId: 'com.example.aiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtnpYneIkaCCa_LGf579d2geGVRL6qzOQ',
    appId: '1:725537660419:web:17a9d8990d95160d7c7836',
    messagingSenderId: '725537660419',
    projectId: 'voicerecognition-31a54',
    authDomain: 'voicerecognition-31a54.firebaseapp.com',
    storageBucket: 'voicerecognition-31a54.appspot.com',
    measurementId: 'G-KYCSRB5KEN',
  );
}
